# Generated by Django 5.1.4 on 2024-12-19 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_en_transito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bodegas.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.producto')),
            ],
            options={
                'unique_together': {('bodega', 'producto')},
            },
        ),
    ]
