# Generated by Django 5.1.4 on 2024-12-19 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodegas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(choices=[('SPOT', 'Spot'), ('CONSIGNACION', 'Consignación')], max_length=20)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='CREADA', max_length=20)),
                ('bodega_destino', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'EXTERNA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrada', to='bodegas.bodega')),
                ('bodega_origen', models.ForeignKey(limit_choices_to={'tipo': 'INTERNA'}, on_delete=django.db.models.deletion.PROTECT, related_name='notas_salida', to='bodegas.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='LineaNotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_recibida_o_consumida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADA', 'Entregada'), ('CONSUMIDA', 'Consumida')], default='PENDIENTE', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.notaventa')),
            ],
        ),
    ]
